/**
 * Skynet stats.js Parser
 *
 * Parses the JavaScript file generated by Skynet's Generate_Stats() function.
 * The file contains:
 *   - SetXxx() functions that set innerHTML of DOM elements (KPI values)
 *   - var arrays populated via .unshift() (chart/table data)
 *
 * Output: A clean JSON object matching our dashboard's data model.
 *
 * Reference: WriteStats_ToJS and WriteData_ToJS in Skynet's firewall.sh
 * https://github.com/Adamm00/IPSet_ASUS/blob/master/firewall.sh
 */

export interface SkynetStats {
  kpi: {
    ipsBanned: number;
    rangesBanned: number;
    inboundBlocks: number;
    outboundBlocks: number;
    monitoringFrom: string;
    monitoringTo: string;
    logSize: string;
  };
  inboundPortHits: { port: number; hits: number }[];
  sourcePortHits: { port: number; hits: number }[];
  lastInboundConnections: SkynetConnection[];
  lastOutboundConnections: SkynetConnection[];
  lastHttpConnections: SkynetConnection[];
  topHttpBlocks: SkynetTopBlock[];
  topInboundBlocks: SkynetTopBlock[];
  topOutboundBlocks: SkynetTopBlock[];
  topBlockedDevices: { hits: number; label: string }[];
}

export interface SkynetConnection {
  ip: string;
  banReason: string;
  alienVaultUrl: string;
  country: string;
  associatedDomains: string[];
}

export interface SkynetTopBlock {
  hits: number;
  ip: string;
  country: string;
}

/**
 * Validate that the raw content looks like a Skynet stats.js file.
 * Returns null if valid, or an error message describing what's wrong.
 */
export function validateStatsJs(raw: string): string | null {
  if (!raw || raw.trim().length === 0) {
    return "Empty response — the stats.js file has no content. Run 'Update Stats' on the router first.";
  }

  // Check if it's HTML (login page, error page, etc.)
  const trimmed = raw.trim().toLowerCase();
  if (trimmed.startsWith("<!doctype") || trimmed.startsWith("<html") || trimmed.startsWith("<head")) {
    return "Received an HTML page instead of stats.js — this usually means the router returned a login page. Check your router credentials (username/password) in Settings.";
  }

  // Check if it's JSON (some routers return JSON errors)
  if (trimmed.startsWith("{") || trimmed.startsWith("[")) {
    return "Received JSON instead of stats.js — the router may have returned an error response. Check the stats path in Settings (default: /ext/skynet/stats.js).";
  }

  // Check for at least one Skynet signature
  const hasSetFunction = /function\s+Set(BLCount1|BLCount2|Hits1|Hits2|StatsDate|StatsSize)\s*\(/i.test(raw);
  const hasUnshift = /\.unshift\(/i.test(raw);
  const hasInnerHTML = /\.innerHTML\s*=/i.test(raw);

  if (!hasSetFunction && !hasUnshift && !hasInnerHTML) {
    // Show a preview of what we got
    const preview = raw.slice(0, 200).replace(/\n/g, "\\n");
    return `File was fetched but doesn't appear to be a valid Skynet stats.js. Expected SetXxx() functions and .unshift() arrays. First 200 chars: "${preview}"`;
  }

  if (!hasSetFunction) {
    return "File contains JavaScript but is missing Skynet KPI functions (SetBLCount1, SetHits1, etc.). This may be a different version of Skynet or the stats haven't been generated yet.";
  }

  return null; // Valid
}

/**
 * Extract a KPI value from a SetXxx() function.
 *
 * Skynet's WriteStats_ToJS produces:
 *   function SetBLCount1() {
 *   	document.getElementById("blcount1").innerHTML = "12345"
 *   }
 *
 * Note: tab indentation, no semicolons on the innerHTML line.
 */
function extractKpiValue(js: string, funcName: string): string {
  // Match the function body and extract the innerHTML value
  // Use [^}]* to match everything inside the function body (including tabs/newlines)
  const regex = new RegExp(
    `function\\s+${funcName}\\s*\\(\\)\\s*\\{[^}]*innerHTML\\s*=\\s*"([^"]*)"`,
    "s"
  );
  const match = js.match(regex);
  return match?.[1] ?? "";
}

/**
 * Extract an array from Skynet's WriteData_ToJS output.
 *
 * Format produced by the shell script:
 *   var DataInPortHits;
 *   DataInPortHits = [];
 *   DataInPortHits.unshift('1234', '567', '89');
 *
 * Key insight: values are single-quoted and separated by "', '"
 * Empty sections produce: VarName.unshift('');
 *
 * IMPORTANT: The regex must NOT use the 's' (dotall) flag, because
 * with dotall, a non-greedy (.+?) on an empty value like .unshift('')
 * would match across newlines to the next '); occurrence, capturing garbage.
 * Since the .unshift() call is always on a single line, we don't need dotall.
 */
function extractArray(js: string, varName: string): string[] {
  // Match the .unshift() call on a SINGLE line (no 's' flag)
  // This prevents the regex from spanning across multiple variable declarations
  const regex = new RegExp(
    `${varName}\\.unshift\\('(.*?)'\\);`
  );
  const match = js.match(regex);
  if (!match?.[1]) return [];

  // Empty data: Skynet writes .unshift('') for empty sections
  const inner = match[1];
  if (inner === "" || inner.trim() === "") return [];

  // Split on "', '" (the values are single-quoted, separated by comma+space)
  return inner.split("', '").map(s => s.trim());
}

/**
 * Parse the monitoring date range from the stats date string.
 * Format: "Monitoring From Feb 15 00:01:23 To Feb 28 23:58:12"
 */
function parseMonitoringDates(dateStr: string): { from: string; to: string } {
  const match = dateStr.match(/Monitoring From (.+?) To (.+)/);
  return {
    from: match?.[1] ?? "",
    to: match?.[2] ?? "",
  };
}

/**
 * Parse the log size from the stats size string.
 * Format: "Log Size - (14M)B" or "Log Size - (2.3M)B"
 */
function parseLogSize(sizeStr: string): string {
  const match = sizeStr.match(/\(([^)]+)\)/);
  return match?.[1] ? `${match[1]}B` : sizeStr;
}

/**
 * Parse port hit data from parallel Data and Label arrays.
 */
function parsePortHits(
  dataArr: string[],
  labelArr: string[]
): { port: number; hits: number }[] {
  const result: { port: number; hits: number }[] = [];
  const len = Math.min(dataArr.length, labelArr.length);
  for (let i = 0; i < len; i++) {
    const port = parseInt(labelArr[i], 10);
    const hits = parseInt(dataArr[i], 10);
    if (!isNaN(port) && !isNaN(hits)) {
      result.push({ port, hits });
    }
  }
  return result;
}

/**
 * Parse connection table data from parallel arrays.
 * Each connection has: IP, BanReason, AlienVault URL, Country, Associated Domains
 */
function parseConnections(
  ips: string[],
  banReasons: string[],
  alienVaults: string[],
  countries: string[],
  domains: string[]
): SkynetConnection[] {
  const result: SkynetConnection[] = [];
  const len = ips.length;
  for (let i = 0; i < len; i++) {
    if (!ips[i] || ips[i] === "") continue;
    result.push({
      ip: ips[i],
      banReason: banReasons[i] ?? "*",
      alienVaultUrl: alienVaults[i] ?? "",
      country: countries[i] ?? "**",
      associatedDomains:
        domains[i] && domains[i] !== "*"
          ? domains[i].split(" ").filter(Boolean)
          : [],
    });
  }
  return result;
}

/**
 * Parse top blocks data from parallel arrays (hits, IPs, countries).
 */
function parseTopBlocks(
  hits: string[],
  ips: string[],
  countries: string[]
): SkynetTopBlock[] {
  const result: SkynetTopBlock[] = [];
  const len = Math.min(hits.length, ips.length);
  for (let i = 0; i < len; i++) {
    if (!ips[i] || ips[i] === "") continue;
    result.push({
      hits: parseInt(hits[i], 10) || 0,
      ip: ips[i],
      country: countries[i] ?? "*",
    });
  }
  return result;
}

/**
 * Parse top blocked devices from parallel arrays (hits + label with device name).
 */
function parseTopDevices(
  hits: string[],
  labels: string[]
): { hits: number; label: string }[] {
  const result: { hits: number; label: string }[] = [];
  const len = Math.min(hits.length, labels.length);
  for (let i = 0; i < len; i++) {
    if (!labels[i] || labels[i] === "") continue;
    result.push({
      hits: parseInt(hits[i], 10) || 0,
      label: labels[i],
    });
  }
  return result;
}

/**
 * Main parser: takes the raw stats.js content and returns structured data.
 *
 * Call validateStatsJs() first to check if the content is valid.
 * This function will still return a best-effort parse even for partial data.
 */
export function parseSkynetStats(js: string): SkynetStats {
  // KPI values
  const blcount1 = extractKpiValue(js, "SetBLCount1");
  const blcount2 = extractKpiValue(js, "SetBLCount2");
  const hits1 = extractKpiValue(js, "SetHits1");
  const hits2 = extractKpiValue(js, "SetHits2");
  const statsDate = extractKpiValue(js, "SetStatsDate");
  const statsSize = extractKpiValue(js, "SetStatsSize");

  const dates = parseMonitoringDates(statsDate);

  // Port hits
  const dataInPort = extractArray(js, "DataInPortHits");
  const labelInPort = extractArray(js, "LabelInPortHits");
  const dataSPort = extractArray(js, "DataSPortHits");
  const labelSPort = extractArray(js, "LabelSPortHits");

  // Connection tables
  const inConnIPs = extractArray(js, "LabelInConn_IPs");
  const inConnBanReason = extractArray(js, "LabelInConn_BanReason");
  const inConnAlienVault = extractArray(js, "LabelInConn_AlienVault");
  const inConnCountry = extractArray(js, "LabelInConn_Country");
  const inConnDomains = extractArray(js, "LabelInConn_AssDomains");

  const outConnIPs = extractArray(js, "LabelOutConn_IPs");
  const outConnBanReason = extractArray(js, "LabelOutConn_BanReason");
  const outConnAlienVault = extractArray(js, "LabelOutConn_AlienVault");
  const outConnCountry = extractArray(js, "LabelOutConn_Country");
  const outConnDomains = extractArray(js, "LabelOutConn_AssDomains");

  const httpConnIPs = extractArray(js, "LabelHTTPConn_IPs");
  const httpConnBanReason = extractArray(js, "LabelHTTPConn_BanReason");
  const httpConnAlienVault = extractArray(js, "LabelHTTPConn_AlienVault");
  const httpConnCountry = extractArray(js, "LabelHTTPConn_Country");
  const httpConnDomains = extractArray(js, "LabelHTTPConn_AssDomains");

  // Top blocks
  const dataTHHits = extractArray(js, "DataTHConnHits");
  const labelTHIPs = extractArray(js, "LabelTHConnHits_IPs");
  const labelTHCountry = extractArray(js, "LabelTHConnHits_Country");

  const dataTIHits = extractArray(js, "DataTIConnHits");
  const labelTIIPs = extractArray(js, "LabelTIConnHits_IPs");
  const labelTICountry = extractArray(js, "LabelTIConnHits_Country");

  const dataTOHits = extractArray(js, "DataTOConnHits");
  const labelTOIPs = extractArray(js, "LabelTOConnHits_IPs");
  const labelTOCountry = extractArray(js, "LabelTOConnHits_Country");

  const dataTCHits = extractArray(js, "DataTCConnHits");
  const labelTCLabels = extractArray(js, "LabelTCConnHits");

  return {
    kpi: {
      ipsBanned: parseInt(blcount1, 10) || 0,
      rangesBanned: parseInt(blcount2, 10) || 0,
      inboundBlocks: parseInt(hits1, 10) || 0,
      outboundBlocks: parseInt(hits2, 10) || 0,
      monitoringFrom: dates.from,
      monitoringTo: dates.to,
      logSize: parseLogSize(statsSize),
    },
    inboundPortHits: parsePortHits(dataInPort, labelInPort),
    sourcePortHits: parsePortHits(dataSPort, labelSPort),
    lastInboundConnections: parseConnections(
      inConnIPs, inConnBanReason, inConnAlienVault, inConnCountry, inConnDomains
    ),
    lastOutboundConnections: parseConnections(
      outConnIPs, outConnBanReason, outConnAlienVault, outConnCountry, outConnDomains
    ),
    lastHttpConnections: parseConnections(
      httpConnIPs, httpConnBanReason, httpConnAlienVault, httpConnCountry, httpConnDomains
    ),
    topHttpBlocks: parseTopBlocks(dataTHHits, labelTHIPs, labelTHCountry),
    topInboundBlocks: parseTopBlocks(dataTIHits, labelTIIPs, labelTICountry),
    topOutboundBlocks: parseTopBlocks(dataTOHits, labelTOIPs, labelTOCountry),
    topBlockedDevices: parseTopDevices(dataTCHits, labelTCLabels),
  };
}
